#
# Percona Mysql Tasks
#
# REQUIRES: percona.repo
---
- yum: pkg=${item} state=installed
  with_items:
  - Percona-Server-client-55
  - Percona-Server-server-55
  - MySQL-python
  tags:
  - mysql.pkgs

- service: name=mysql enabled=yes state=started
  ignore_errors: yes
  tags:
  - mysql.srv

- template: dest=/etc/my.cnf
  first_available_file:
  - ${playbook_templates_private}/${playbook}/my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/my.cnf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/my.cnf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/my.cnf.j2
  - ${playbook_templates}/${playbook}/my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/my.cnf.j2-${host_group}
  - ${playbook_templates}/${playbook}/my.cnf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/my.cnf.j2
  notify:
  - restart mysql
  tags:
  - mysql.cfg

- mysql_user: host=${item} name=root password=${mysql_root_passwd}
  with_items:
  - ${ansible_fqdn}
  - 127.0.0.1
  - ::1
  - localhost
  ignore_errors: yes
  tags:
  - mysql.init.root

- mysql_user: host=localhost name=${mysql_user} password=${mysql_passwd} priv=*.*:ALL state=present
  ignore_errors: yes  
  tags:  
  - mysql.init.user  
  
- mysql_db: name=${item} state=present  
  with_items: ${databases}
  ignore_errors: yes
  tags:
  - mysql.init.db

- template: dest=/root/.my.cnf
  first_available_file:
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${host_group}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2
  tags:
  - mysql.cfg
